version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: user-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    environment:
      PORT: 3005
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: users_db
      JWT_SECRET: supersecretkey
  
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service
    environment:
      PORT: 8000
      JWT_SECRET: supersecretkey
  
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  

  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/restaurants_db

  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - redis
    environment:
      PORT: 3002
      MONGO_URI: mongodb://mongodb:27017/menu_db
      REDIS_HOST: redis
  
  order-postgres:
    image: postgres:15
    container_name: order-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
  
  order_service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3003:3003"
    depends_on:
      - order-postgres
      - redis
    environment:
      PORT: 3003
      DB_HOST: order-postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: orders_db
      REDIS_HOST: redis

volumes:
    postgres_data:
    mongo_data: