apiVersion: batch/v1
kind: Job
metadata:
  name: user-db-init
spec:
  template:
    spec:
      containers:
      - name: init
        image: postgres:15
        command: ["sh", "-c"]
        args:
          - |
            psql postgresql://admin:admin@postgres:5432/users_db -f /scripts/schema.sql
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: user-schema